export const ROLE_ADMIN = 'ADMIN';
export const ROLE_MANAGER = 'MANAGER';
export const ROLE_CONSULTANT = 'CONSULTANT';
export const ROLE_EMPLOYEE = 'EMPLOYEE';

export const CATALOG_MANAGER_ROLES = [ROLE_ADMIN, ROLE_MANAGER];

export const ASSIGNABLE_ROLES = [ROLE_CONSULTANT, ROLE_EMPLOYEE];

export const APPROVER_ROLES = [ROLE_ADMIN, ROLE_MANAGER];
